### ISSUE TITLE
can't compile ionic app - error TS2304: Cannot find name 'ScrollingCamera'.

### ISSUE THREAD

**Issue by leabdalla** [jjcapellan/Phaser3-ScrollingCamera#2]
I've download the script file and added to my HTML:

    <body>
      <app-root></app-root>
      <script src="/assets/scripts/scrollcam.min.js"></script>
    </body>

So in my Scene I've added:

    ...
    export class BlankSceneService extends Phaser.Scene {
        public myCamera = new ScrollingCamera(this);
        ...

but when I try to compile my Ionic 4 app, it stops on this error:

    [ng] ERROR in src/app/services/blank-scene.service.ts(17,25): error TS2304: Cannot find name 'ScrollingCamera'.

It looks like I need to `import` this class in scene script.

Is that correct? How can I do that?

**Comment by jjcapellan** [comment]
Sorry for the delay, I just happened to see this issue a few days ago.
I have released a new version (2.0.0) that you can install as a module, so you shouldn't have any problem.
Please note that the new version is not compatible with the old one.
More info in the readme.
