### ISSUE TITLE
Scrolling long areas no longer work since v2.0

### ISSUE THREAD

**Issue by josephbaril** [jjcapellan/Phaser3-ScrollingCamera#3]
This seems very recent, camera worked fine before it was added to npm. 
In a new project but using same camera configuration, the camera now gets stuck while scrolling vertically on large areas (multiple times bigger then my scene.)

It gets to a state where scrolling will no longer work.

**Comment by jjcapellan** [comment]
Hi @josephbaril ,
In this version the api has been changed. Now, the object **contentBounds** is used to define the scrolling area.
This was necessary to manage the orientation of the scroll (vertical/horizontal).
Please, read the readme for more details about the new config parameters.
If you prefer, you still can use the pevius version (v1.0.2) from here:
https://cdn.jsdelivr.net/gh/jjcapellan/Phaser3-ScrollingCamera@1.0.2/dist/scrollcam.min.js

Greetings.

**Comment by josephbaril** [comment]
![kRuibt3fbm](https://user-images.githubusercontent.com/5166217/99547536-a32da980-2985-11eb-9227-2b90e3d34564.gif)
I attached a gif of what happens, I truly think it's a bug, I tried using many different configs. This example uses : 
`const cameraConfig = {
      wheel: {
        // Mouse wheel params (optional)
        enable: false, // Does this camera use the mouse wheel? (default = false)
      },
      drag: 0.9, // Reduces the scroll speed per game step in 10%. (default = 0.95)
      vertical: true, // Does this camera use horizontal scroll (default = false)
      horizontal: false,
      contentBounds: {
        // Determines the limits of the area where the camera is looking. (optional)
        x: 0, // x position of contents from top-left origin (default = cameraOptions.x)
        y: 0, // y position of contents from top-left origin (default = cameraOptions.y)
        length: 7000, // Distance measured in pixels along the camera main axis
      },
    };`

Changing the length of the contentBounds does not seem to affect it, it always gets stuck at about the same height.

Thanks for your fast reply :)

**Comment by jjcapellan** [comment]
Hi again @josephbaril ,
Are you using the latest version (2.0) ?
I have tested your config with a vertical content of 7000 pixels, and it works:
https://codepen.io/jjcapellan/pen/yLJrGRX
Please, if the above example doesn't help you, show me a minimal code to reproduce the bug. 
P.S.: The config object has not "vertical" property, only horizontal (true/false).
But, yes, there is a bug: I just checked that the mouse wheel was not disabled :) .

Good luck !!
