### ISSUE TITLE
the image I want to scroll duplicates

### ISSUE THREAD

**Issue by dev0banana** [jjcapellan/Phaser3-ScrollingCamera#5]
Hello, if I use your scroller, the image I want to scroll duplicates. how to solve the problem?

my greetings

**Comment by jjcapellan** [comment]
Hi @Bananedansunjeu ,
You have two alternatives:
1) Place the image at coordinates outside of the game.
2) Use the "ignore" method for the main camera. (ex: this.cameras.main.ignore(imageObject))

For alternative 1, the readme image is very descriptive.
For alternative 2 take a look to this example: https://codepen.io/jjcapellan/pen/BaZzXyJ

I hope this helps you.
Best regards.
