### ISSUE TITLE
Can this use for moving main camera by dragging map

### ISSUE THREAD

**Issue by kyoa** [jjcapellan/Phaser3-ScrollingCamera#7]
As title

**Comment by jjcapellan** [comment]
It could be used, but it would be limited to one direction only (horizontal or vertical). My initial motivation was to create a function to navigate through menu options on the phone.

This example by @Samme shows how to move the camera in all directions by dragging:
https://codepen.io/samme/pen/XWJxgRG

Wow, 2022 !!. My apologies for my late reply.
